services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      target: prod
    ports:
      - "${BACKEND_PORT}:80"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/login"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  db:
    image: mariadb:10.11
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin --silent ping -h 127.0.0.1 -uroot -p\"$MYSQL_ROOT_PASSWORD\" >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
