services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      target: prod
    ports:
      - "${BACKEND_PORT}:80"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      target: prod
    depends_on:
      - backend

volumes:
  db_data:
